src_vocab_size: 32000
tgt_vocab_size: 32000
d_model: 512
num_heads: 8
num_layers: 6
d_ff: 2048
dropout: 0.1
pad_idx: 0
lr: 0.0001
weight_decay: 0.01
step_size: 1
gamma: 0.95
batch_size: 8
epochs: 10
save_dir: checkpoints
data_path: data/translation2019zh_train.json
num_workers: 8
grad_clip: 1.0
